# Generated by Django 6.1 on 2026-08-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="📚", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("etymology", "Raíces y Etimología"),
                            ("periphrasis", "Perífrasis Verbales"),
                            ("phonetics", "Fonética y AFI"),
                            ("punctuation", "Signos de Puntuación"),
                            ("connectors", "Conectores y Cohesión"),
                            ("rhetoric", "Figuras Retóricas"),
                            ("comparison", "Fórmulas de Comparación"),
                            ("description", "Fórmulas de Descripción"),
                            ("exposition", "Fórmulas de Exposición"),
                            ("argumentation", "Fórmulas de Argumentación"),
                            ("narration", "Fórmulas de Narración"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("root", models.CharField(max_length=100)),
                ("meaning", models.TextField()),
                ("example", models.TextField(blank=True, default="")),
                ("breakdown", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
    ]
