# Generated by Django 6.1 on 2026-08-28 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(default="📚", max_length=50)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etymology", "Raíces y Etimología"),
                            ("periphrasis", "Perífrasis Verbales"),
                            ("phonetics", "Fonética y AFI"),
                            ("punctuation", "Signos de Puntuación"),
                            ("connectors", "Conectores y Cohesión"),
                            ("rhetoric", "Figuras Retóricas"),
                            ("comparison", "Fórmulas de Comparación"),
                            ("description", "Fórmulas de Descripción"),
                            ("exposition", "Fórmulas de Exposición"),
                            ("argumentation", "Fórmulas de Argumentación"),
                            ("narration", "Fórmulas de Narración"),
                            ("grammar", "Gramática del Castellano"),
                            ("syntax", "Sintaxis del Castellano"),
                            ("literature", "Literatura Hispanoamericana"),
                            ("poetry", "Poesía Castellana"),
                            ("orthography", "Ortografía Castellana"),
                            ("writing", "Redacción Avanzada"),
                            ("communication", "Comunicación Escrita"),
                            ("academic", "Redacción Académica"),
                            ("scientific", "Redacción Científica"),
                            ("journalism", "Redacción Periodística"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("root", models.CharField(max_length=200)),
                ("meaning", models.TextField()),
                ("example", models.TextField(blank=True, default="")),
                ("breakdown", models.TextField(blank=True, default="")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Opción Múltiple"),
                            ("true_false", "Verdadero/Falso"),
                            ("fill_blank", "Completar"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("option_a", models.CharField(blank=True, default="", max_length=500)),
                ("option_b", models.CharField(blank=True, default="", max_length=500)),
                ("option_c", models.CharField(blank=True, default="", max_length=500)),
                ("option_d", models.CharField(blank=True, default="", max_length=500)),
                (
                    "correct_answer",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                ("points", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Estudiante"),
                            ("teacher", "Profesor"),
                            ("admin", "Administrador"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("max_streak", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("score", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
