# Generated by Django 4.2.7 on 2026-09-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("puntuacion", models.PositiveIntegerField(default=0)),
                ("ejercicios_completados", models.PositiveIntegerField(default=0)),
                ("total_ejercicios", models.PositiveIntegerField(default=0)),
                ("porcentaje", models.PositiveIntegerField(default=0)),
                ("codigo_verificacion", models.CharField(max_length=50, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="core.course",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="core.lesson",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
