# Generated by Django 5.2.11 on 2026-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logro_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='logro',
            name='tipo',
            field=models.CharField(choices=[('insignia', 'Insignia'), ('medalla', 'Medalla'), ('estrella', 'Estrella'), ('libro', 'Libro')], default='insignia', max_length=20),
        ),
    ]
