# Generated by Django 5.2.11 on 2026-10-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inscripcion_options_alter_logro_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso_completado', 'Curso completado'), ('evaluacion', 'Evaluacion recibida'), ('certificado', 'Certificado emitido'), ('logro', 'Logro desbloqueado'), ('inscripcion', 'Nueva inscripcion'), ('info', 'Informacion')], default='info', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
