from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('registro/', views.registro, name='registro'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('cursos/', views.course_list, name='course_list'),
    path('buscar/', views.buscar, name='buscar'),
    path('recursos/', views.resource_list, name='resource_list'),
    path('curso/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('practicar/<int:lesson_id>/', views.practice_lesson, name='practice_lesson'),
    path('api/leccion/<slug:course_slug>/<int:lesson_order>/', views.get_lesson_data, name='get_lesson_data'),
    path('api/guardar-progreso/', views.save_lesson_progress, name='save_progress'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('ranking/', views.ranking_global, name='ranking_global'),
    path('ranking/curso/<slug:curso_slug>/', views.ranking_curso, name='ranking_curso'),
    path('profesor/ranking/', views.ranking_profesor, name='ranking_profesor'),
    path('perfil/', views.perfil, name='perfil'),
    path('notificaciones/', views.notificaciones_lista, name='notificaciones_lista'),
    path('notificaciones/leer/<int:notif_id>/', views.notificacion_leer, name='notificacion_leer'),
    path('notificaciones/marcar-todas/', views.notificaciones_marcar_todas, name='notificaciones_marcar_todas'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='core/password_change.html', success_url='/es/perfil/'), name='password_change'),
    path('profesor/', views.teacher_dashboard, name='teacher_dashboard'),
    path('profesor/curso/<slug:curso_slug>/', views.teacher_course_students, name='teacher_course_students'),
    path('profesor/curso/nuevo/', views.teacher_course_edit, name='teacher_course_new'),
    path('profesor/curso/<slug:curso_slug>/editar/', views.teacher_course_edit, name='teacher_course_edit'),
    path('profesor/curso/<slug:curso_slug>/borrar/', views.teacher_course_delete, name='teacher_course_delete'),
    path('profesor/curso/<slug:curso_slug>/lecciones/', views.teacher_course_lessons, name='teacher_course_lessons'),
    path('profesor/curso/<slug:curso_slug>/leccion/nueva/', views.teacher_lesson_edit, name='teacher_lesson_new'),
    path('profesor/curso/<slug:curso_slug>/leccion/<int:lesson_id>/editar/', views.teacher_lesson_edit, name='teacher_lesson_edit'),
    path('profesor/curso/<slug:curso_slug>/leccion/<int:lesson_id>/borrar/', views.teacher_lesson_delete, name='teacher_lesson_delete'),
    path('profesor/curso/<slug:curso_slug>/estudiante/<int:user_id>/', views.teacher_student_detail, name='teacher_student_detail'),
    path('profesor/curso/<slug:curso_slug>/estudiante/<int:user_id>/evaluar/', views.teacher_evaluate, name='teacher_evaluate'),
    path('profesor/curso/<slug:curso_slug>/estudiante/<int:user_id>/certificar/', views.teacher_certify, name='teacher_certify'),
    path('profesor/curso/<slug:curso_slug>/estudiante/<int:user_id>/progreso.pdf', views.teacher_student_progress_pdf, name='teacher_student_progress_pdf'),
    path('profesor/leccion/<int:lesson_id>/', views.teacher_lesson_detail, name='teacher_lesson_detail'),
    path('profesor/ejercicio/editar/<int:exercise_id>/', views.teacher_exercise_edit, name='teacher_exercise_edit'),
    path('profesor/ejercicio/nuevo/', views.teacher_exercise_edit, name='teacher_exercise_new'),
    path('profesor/ejercicio/eliminar/<int:exercise_id>/', views.teacher_exercise_delete, name='teacher_exercise_delete'),
    path('certificado/leccion/<int:leccion_id>/', views.generar_certificado, name='certificado_leccion'),
    path('certificado/curso/<slug:curso_slug>/', views.generar_certificado, name='certificado_curso'),
    path('certificado/pdf/<slug:curso_slug>/', views.descargar_certificado_pdf, name='certificado_pdf'),
    path('certificado/docx/<slug:curso_slug>/', views.descargar_certificado_docx, name='certificado_docx'),
    path('informe/progreso/', views.descargar_informe_progreso, name='informe_progreso'),
]
